export const AGELESS_PRICING_PLANS = [
  {
    id: "general-admission",
    label: "General Admission (GA)",
    labelLines: ["General Admission", "(GA)"],
    priceLabel: "Early Bird",
    price: "$399",
    regularPriceLabel: "Regular",
    regularPrice: "$420",
    items: [
      "Full summit access",
      "Keynote sessions",
      "General networking areas",
    ],
    featured: false,
  },
  {
    id: "pitch-room-access",
    label: "Pitch Room Access",
    labelLines: ["Pitch Room", "Access"],
    priceLabel: "Early Bird",
    price: "$440",
    regularPriceLabel: "Regular",
    regularPrice: "$525",
    items: [
      "Exclusive founder pitch sessions",
      "Investor rooms",
      "Specialized showcases",
    ],
    featured: false,
  },
  {
    id: "ga-vip-dinner",
    label: "VIP Experience",
    labelLines: ["VIP", "Experience"],
    priceLabel: "Early Bird",
    price: "$1,250",
    regularPriceLabel: "Regular",
    regularPrice: "$1,999",
    items: [
      "Full summit access",
      "Exclusive intimate evening networking dinner",
      "Networking with speakers and key figures",
    ],
    featured: false,
  },
  {
    id: "become-a-sponsor",
    label: "Become A Sponsor / Exhibitor",
    labelLines: ["Become A Sponsor /", "Exhibitor"],
    price: "Custom / Inquiry",
    items: [
      "Premium brand placement",
      "Dedicated activation space",
      "High-level B2B networking opportunities",
      "Ageless Evolution platform presence",
    ],
    featured: false,
  },
] as const;
